site_name: {{cookiecutter.project_name}} documentation
repo_url: https://github.com/sg-s/cookiecutter-python
site_author: Srinivas Gorur-Shandilya
site_url: https://inscopix.github.io/{{cookiecutter.project_name}}/


docs_dir: 'docs'
theme:
  name: material
  logo: 'logo.png'
  palette:
    primary: '#87C440'
    accent: '#3D97CD'
  features:
    - navigation.tracking
    - toc.follow
    - navigation.top


 
nav:
  - Home:  README.md


use_directory_urls: false

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - codehilite
  - mkautodoc
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - pymdownx.snippets



extra:
  homepage: https://srinivas.gs
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<code@srinivas.gs>
      name: Srinivas Gorur-Shandilya
    - icon: fontawesome/brands/github
      link: https://github.com/sg-s/


plugins:
  - mkdocs-jupyter
  - search

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: 
  - extras/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - extras/extra.js

extra_css:
  - extras/extra.css


hooks:
  - hooks/gen_sym_links.py

