name: check-doc-strings

on:
  pull_request:
    branches: [ main ]
  push:


jobs:

  check_doc_strings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run Interrogate locally
        run: |
          if [ $(interrogate -c pyproject.toml -v . -f 100 | grep "FAILED" | wc -l) = 1 ]; then
             echo "necessary docstrings missing:"
             interrogate -vv . -f 100 
             exit 1
          fi


